#!/usr/bin/env bash
set -euo pipefail

tmp_dir="$(mktemp -d)"
tmp_override="${tmp_dir}/comments-test-override.yml"
tmp_site="${tmp_dir}/site"

cleanup() {
  rm -rf "${tmp_dir}"
}
trap cleanup EXIT

cat >"${tmp_override}" <<'YAML'
giscus:
  repo: alshedivat/al-folio
  repo_id: R_kgDOExample
  category: Comments
  category_id: DIC_kwDOExample
YAML

bundle exec jekyll build --config "_config.yml,${tmp_override}" -d "${tmp_site}" >/dev/null

giscus_page="${tmp_site}/blog/2022/giscus-comments/index.html"
disqus_page="${tmp_site}/blog/2015/disqus-comments/index.html"

# 이 검사는 al-folio가 스캐폴드와 함께 제공하는 데모 글(blog/2022/giscus-comments,
# blog/2015/disqus-comments)이 있어야 동작한다. 개인 사이트에서 데모 글을 지우면
# 대상 페이지가 생성되지 않아 코드 문제가 없는데도 실패한다.
# 따라서 대상 페이지가 없으면 건너뛴다. 나중에 댓글 기능을 쓰는 글이 생기면
# 자동으로 다시 검증된다.
checked=0

if [ -f "${giscus_page}" ]; then
  grep -q 'https://giscus.app/client.js' "${giscus_page}"
  if grep -q 'giscus comments misconfigured' "${giscus_page}"; then
    echo "unexpected giscus misconfiguration warning in ${giscus_page}" >&2
    exit 1
  fi
  checked=$((checked + 1))
else
  echo "skipping giscus check: ${giscus_page#"${tmp_site}"} not generated by this site"
fi

if [ -f "${disqus_page}" ]; then
  grep -q 'id="disqus_thread"' "${disqus_page}"
  grep -q '.disqus.com/embed.js' "${disqus_page}"
  checked=$((checked + 1))
else
  echo "skipping disqus check: ${disqus_page#"${tmp_site}"} not generated by this site"
fi

if [ "${checked}" -eq 0 ]; then
  echo "comments integration checks skipped (no sample comment posts in this site)"
else
  echo "comments integration checks passed"
fi
